version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "4000:4000"
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: batismart
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
